apiVersion: miniocontroller.min.io/v1beta1
kind: ClusterServiceVersion
metadata:
  name: miniooperator.v1.0.3
  namespace: placeholder
  annotations:
    capabilities: "Full Lifecycle"
    categories: "Storage"
    description: "Deploy and Manage Distributed MinIO Clusters"
    containerImage: minio/k8s-operator:1.0.3
    repository: https://github.com/minio/minio-operator
    createdAt: 2019-09-21T00:00:00Z
    certified: "true"
    support: MinIO, Inc.
    alm-examples: |-
      [
        {
          "apiVersion": "v1",
          "kind": "Secret",
          "metadata": {
            "name": "minio-creds-secret"
          },
          "data": {
              "accesskey": "bWluaW8=",
              "secretkey": "bWluaW8xMjM="
          }
        },
        {
          "apiVersion": "miniocontroller.min.io/v1beta1",
          "kind": "MinIOInstance",
          "metadata": {
            "name": "minio"
          },
          "spec": {
            "replicas": "4",
            "credsSecret": {
              "name": "minio-creds-secret"
            },
            "requestAutoCert": "false"
          }
        }
      ]
spec:
  name: minio-operator
  maturity: beta
  version: 1.0.3
  displayName: MinIO Operator
  description: |
    MinIO Operator provides native integration with Kubernetes. It allows users to create S3 API Compatible, high performance, highly scalable object storage clusters on demand. 

    MinIO Operator provides the following features:

    * **Deploy**: Launch MinIO Clusters with specific affinity, toleration and other pre-defined settings.

    * **Automatic TLS**: Deploy TLS enabled MinIO clusters with builtin certificate signing requests.

    * **Configure**: Configure the fundamentals of MinIO like versions, persistence, erasure code configuration, and replicas.

  keywords: ['minio', 's3', 'object storage', 'private cloud', 'cloud storage']
  
  maintainers:
  - name: MinIO, Inc.
    email: dev@min.io
  provider:
    name: MinIO, Inc.
  links:
  - name: MinIO
    url: https://www.min.io/
  - name: MinIO Documentation
    url: https://docs.min.io
  - name: MinIO Operator
    url: https://github.com/minio/minio-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAKcAAACnCAYAAAB0FkzsAAAACXBIWXMAABcRAAAXEQHKJvM/AAAIiklEQVR4nO2dT4hVVRzHj2kJOkqKf8qCogmzSEOoRdGi7C+1qDZtKqIIshYtEpwgqYiCEgwMtFxVZJsKrE0RleGiZpFRFMi0GHPASrOcUsdQM+N7myfPN++ce9/9897v3fP5gAvnvblv7syH3z2/3/mdc6YNX3n7KQdgjx1n8UcBqyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEsyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEsyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEs8zgT1MNM5csdjMvWJxc+9jP+92xX/bX7yYrBjlLREKe/8Ddbt6q69zMJYvOuPDJIxPu4OfDbt/WbW5iZHef32l3YK+kkrjw8fvdhY/dl+liBz78zI29/Lr75/BEH9xZz2CvpKLMmDPbrXh/U2YxxcK7bnbL39/sZi+7xOptmQA5CzL44ho367LOJdNj/4o31iNoAOQswMK7bnHzbrw29wWmD8x2Szc+m0RfmApyFkDjzKIogpZxnTpCtp6T+auunZKRN3Psl9/cgQ8/Tb4y95oVbu7Vy73vPe/+u93B7cPu0Nff27rJHoOcOZm1bND7jUd/3O12PbT2jGx88IU1SSLkQ69/e9uDNm+2R/BYz4mioY8fn3h+SplodN2GpITkg8f7VJCzAnyzQWmCqhylQj78D3JWQEiwNEFVmoL/Qc6chJKXi596NHjRkKBKnFSiAuTMzdGRUe+3qvapBCdESFDJTe0TOXOj0o/KRT6UmacJqvl1ZfatqDhPcoSchZBcIdIEVUavklM7QVX7jH1qc/ojiy59zsDP0Zf8/dNeN2PugBtYscz740swvefPL79p+/q/x0+4Pz7e4c69/mp39oJ5Z7w256rL3f53P4r11ztG5CzInpe3tI18zSgKhpIcXwRVQ4n6Q2MFOUvA92huZvCFJzMJqqbkZjT2jDU5Qs4SCI0dm8kjqJKji4ZW27vpLoCcJVGWoFrC0SqoEqvQdGldQc4SkaCqX7Y+mlvJI+jFQ+HCfh0hWy+ZE7+Pu7++3OkW3HGDO+ucc7wXV8ud6qS+SNt6HWXykvXI9yN98XsoAbL1KmgX+dqhmaBQLVPXGX16w+n/KzmKqTEEOSsii6BKdtLWEWkmanTdK6ffnzZvXyeQs0LKElQd9Q1BNW8fS3KEnBVThaBpc/Z1gYSoCzSSm8X33un9MCU9Sn70Pr2/HUqelEQlyz2mTav7miMSom6RJDeTkc9HI4KGZoQUQfe+9k4yrVn3mSMiZxdpRD6VkXwogqoJRM0gagpphyLmqePH3cnDE94oWwPGkLPLZBFUNc2zF8x349uHve9RvbPGYjoe6z2iObnxoXFl7Ms1kLNHSNCx9VuCHx77cg3k7BKKgq2R8Ne3PwiuxFSCdN4D99Ti/vOAnBWjseXKT95Kmj0aOx03o0aRQzt/8P4QNBtD6WgOXGWhpRufCe6pJDR/7ivSK3rGOvZEzgpQg8bKT94Mbt7VjHYI0SPeR4y9nA45y0XTj53uctzgwAefel+bf1P+PUD7GeQsCY0Nl7+3Kdcux24yevrGnnq0x7iHEnIWRKUejS0vWlu8lS00V94umao7yFkAPcZ18EDWsWUaITlj3GCBzWNzogxa5aFuMX3OQP/9kgqCnDno5MwhyA9ydkja9tlQHow5O6BqMUMZeWjLxbqCnBlonNKWRcy0TRVChJKeGI8iRM4MqFSUVr/U9OOuh4eS1ZJ50YGuPmI8BgY5U9CjPE3MxtEuRQTSFKVvDr5INO5nSIgCZBljtjtzKA+hnYxjPTyLyOlBsnRLTLXVhQr5oaaQOoOcbVCBPa2OWZaYSrZCx7tovt13rlHdQc4WlDGnzfyUKaaSLTV2+Ni7eWuhz+hnkLMJyaIjpkOUJWajGTmUbClqxnxYKwlRE0tffTbYtV6WmBo2aPFaKGKqNNW8w1yMIOck6scMJSWJLOs2FBJT5SJFyyxdTHte2hLtWLMBck6OM9P6MXUSsLaUKULW1rp9W7Uq098ZHwuMOTPs2qb15d0a+2mpsI6PASJnUs8MJSXjXwx3rc6oDbpizs5biVpOZcyhdeHa06iTpERjyjzrzDWe1bAh5sy8HVHLmZYxZ02AJKUicJ7lGhpfKlrG2HWURrRySihtYe1D0qRFsiSRGlqdS0oNF8jIw0QrZ+hcHz3OQ2M/DQeyzL23Q4V1XZtHeDpRyqkieCgJ0lHV7R6zRaR0k9GYTDw7UcoZbE/b+cOUhmFNa+p7dPpvERhXdkZ0cipqhqYom7NzSaktCJWBhxInqIbo5AxFTRXAlaAgpQ2ikjO0FMIlY8Jtibx5pGwkUdo2hjXt5RCVnKGoqUJ4Wm9lOxpSNubCQ58BnRGNnMq0Q/XIolJC+UQjZ1nbVyNl94hGztCa8CwgZfeJQk6tbkzbl90HUvaOKOTMEzWRsvfEETk72FNdWbsaMpCy99ReTnUOZcnEJaWaive9vY1pRiPUXs60M3yQ0i61l9N3hg9S2qfWcmqOvLU1Din7h1rL2Rw1kbL/qLWcs5YNImUfU2s5tY/6t7c+iJR9Sq3lLLIFNvQedvwAsyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEsyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEsyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEsyBnyYxv/yrZnwmKg5wlMzGy2+16aC2ClgByVgCClgNyVgSCFgc5KwRBi4GcFYOg+UHOLnBa0MNHan+vZRLVkda9RILqH2SHyAlmQU4wC3KCWZATzIKcYBbkBLMgJ5gFOcEsyAlmQU4wC3KCWZATzIKcYBbkBLMgJ5gFOcEsyAlmQU4wC3KCWZATzIKcYBbkBLMgJ5gFOcEsyAlm0Y4fO/jzgDmc++4/lMShHD6Q8iYAAAAASUVORK5CYII=
    mediatype: image/png
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      deployments:
        - name: minio-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                k8s-app: minio-operator
            template:
              metadata:
                labels:
                  k8s-app: minio-operator
              spec:
                containers:
                    image: 'minio/k8s-operator:1.0.3'
                    imagePullPolicy: Always
                    name: minio-operator
                    resources:
                      limits:
                        cpu: 200m
                        memory: 100Mi
                      requests:
                        cpu: 100m
                        memory: 50Mi
                serviceAccountName: minio-operator-sa
      permissions:
        - serviceAccountName: minio-operator-sa
          rules:
            - apiGroups:
              - ""
              resources:
              - namespaces
              - secrets
              - pods
              - services
              - events
              verbs:
              - get
              - watch
              - create
              - list
              - patch
            - apiGroups:
              - apps
              resources:
              - statefulsets
              verbs:
              - get
              - create
              - list
              - patch
              - watch
            - apiGroups:
              - "certificates.k8s.io"
              resources:
              - "certificatesigningrequests"
              - "certificatesigningrequests/approval"
              - "certificatesigningrequests/status"
              verbs:
              - update
              - create
              - get
            - apiGroups:
              - miniocontroller.min.io
              resources:
              - "*"
              verbs:
              - "*"
            - apiGroups:
              - min.io
              resources:
              - "*"
              verbs:
              - "*"
  customresourcedefinitions:
    owned:
    - name: minioinstances.miniocontroller.min.io
      group: miniocontroller.min.io
      description: A configuration file for a MinIO installation.
      displayName: MinIO Instance
      kind: MinIOInstance
      version: v1beta1
      resources:
      - kind: StatefulSet
        version: apps/v1
      - kind: Pod
        version: v1
      - kind: Service
        version: v1
      - kind: Secret
        version: v1
      specDescriptors:
      - displayName: Size
        description: "Determines the number of MinIO Pods"
        path: replicas
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:label'
      - displayName: Credential Secret
        description: "The secret with credentials to be used for MinIO Cluster"
        path: credsSecret
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:label'
  